services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    volumes:
      - ./shared/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - shared

networks:
  shared:
    external: true