services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    volumes:
      # Mount main nginx conf wrapper
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro 

      # Mount conf.d dir (site specific configs)
      - ./nginx/${NGINX_CONF_DIR:-conf.d}:/etc/nginx/conf.d:ro

      # Mount the snippets directory
      - ./nginx/snippets:/etc/nginx/snippets:ro
      
      - nginx_proxy_logs:/var/log/nginx 
    ports:
      - "80:80"
    networks:
      - shared_network_ref

networks:
  shared_network_ref:
    external: true
    name: shared_network

volumes:
  nginx_proxy_logs: