services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    volumes:
      - ./shared/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_proxy_logs:/var/log/nginx 
    ports:
      - "80:80"
    networks:
      - shared

networks:
  shared:
    driver: bridge
    name: shared_network

volumes:
  nginx_proxy_logs: