services:
  main-frontend:
    build: ./frontend
    image: main-frontend:latest
    container_name: main-frontend
    restart: unless-stopped
    networks:
      - shared_network_ref

networks:
  shared_network_ref:
    external: true
    name: shared_network