services:
  fsp-frontend:
    build: ./frontend
    image: fsp-frontend:latest
    container_name: fsp-frontend
    ports:
      - "4200:80"
    networks:
      - shared

  fsp-backend:
    build: ./backend
    image: fsp-backend:latest
    container_name: fsp-backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fsp-db-host:5432/fspdb
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - fsp-db-host
    networks:
      - shared

  fsp-db-host:
    image: postgres:17
    container_name: fsp-db
    environment:
      - POSTGRES_DB=fspdb
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - shared

networks:
  shared:
    external: true
