services:
  fsp-frontend:
    build: ./frontend
    image: fsp-frontend:latest
    ports:
      - "4200:80"
    networks:
      - shared

  fsp-backend:
    build: ./backend
    image: fsp-backend:latest
    ports:
    - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fsp-db-host:5432/fspdb
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - APP_URL_FRONTEND=http://fsp.patrickdd.com
      - APP_URL_BACKEND=http://fsp.patrickdd.com/api

    depends_on:
      - fsp-db-host
    networks:
      - shared

  fsp-db-host:
    image: postgres:17
    environment:
      - POSTGRES_DB=fspdb
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - shared

networks:
  shared:
    external: true