services:
  fsp-frontend:
    image: fsp-frontend:latest
    ports:
      - "4200:80"
    networks:
      - shared

  fsp-backend:
    image: fsp-backend:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fsp-db-host:5432/fspdb
      - SPRING_DATASOURCE_USERNAME=webapps
      - SPRING_DATASOURCE_PASSWORD=securepass
    depends_on:
      - fsp-db-host
    networks:
      - shared

  fsp-db-host:
    image: postgres:17
    environment:
      - POSTGRES_DB=fspdb
      - POSTGRES_USER=webapps
      - POSTGRES_PASSWORD=securepass
    ports:
      - "5433:5432"
    networks:
      - shared

networks:
  shared:
    external: true
