services:
  fsp-frontend:
    build: ./frontend
    ports:
      - "4200:80"
    networks:
      - shared

  fsp-backend:
    build: ./backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - shared

  fsp-db-host:
    image: postgres:17
    environment:
      - POSTGRES_DB=fspdb
      - POSTGRES_USER=webapps # Test credentials, not for production use
      - POSTGRES_PASSWORD=securepass
    networks:
      - shared

networks:
  shared:
    external: true
