events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=10s;

    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;

    include /etc/nginx/conf.d/*.conf; 
    include /etc/nginx-hidden/conf.d/*.conf;
}