name: main domain CI/CD Pipeline

on:
  push:
    branches:
      - main
      - cicd
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  show_directory:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List directory contents
        run: |
          echo "Repository structure:"
          ls -la

      - name: Show working directory path
        run: |
          echo "Current working directory:"
          pwd
          echo "Contents:"
          find . -type d -ls
