server {
    listen 80;
    server_name portfolio.patrickdd.com portfolio.patrickdumdum.com;

    location /api/ {
        set $upstream_portfolio_backend http://portfolio-backend:8080;
        proxy_pass $upstream_portfolio_backend;
        include snippets/proxy_params.conf;
    }

    location / {
        set $upstream_portfolio_frontend http://portfolio-frontend:80; 
        proxy_pass $upstream_portfolio_frontend;
        include snippets/proxy_params.conf;
    }
}