server {
    listen 80;
    server_name template.patrickdd.com template.patrickdumdum.com;

    location /api/ {
        set $upstream_template_backend http://template-backend:8080;
        proxy_pass $upstream_template_backend;
        include snippets/proxy_params.conf;
    }

    location / {
        set $upstream_template_frontend http://template-frontend:80; 
        proxy_pass $upstream_template_frontend;
        include snippets/proxy_params.conf;
    }
}