server {
    listen 80;
    server_name patrickdd.test patrickdumdum.test;

    location /api/ {
        set $upstream_admin_backend http://admin-backend:8080;
        proxy_pass $upstream_admin_backend;
        include snippets/proxy_params.conf;
    }

    location / {
        set $upstream_admin_frontend http://admin-frontend:80; 
        proxy_pass $upstream_admin_frontend;
        include snippets/proxy_params.conf;
    }
}