server {
    listen 80;
    server_name statify.patrickdd.com statify.patrickdumdum.com;

    location /api/ {
        set $upstream_statify_backend http://statify-backend:8080;
        proxy_pass $upstream_statify_backend;
        include snippets/proxy_params.conf;
    }

    location / {
        set $upstream_statify_frontend http://statify-frontend:80; 
        proxy_pass $upstream_statify_frontend;
        include snippets/proxy_params.conf;
    }
}