name: CI/CD for webapps

on:
  push:
    branches:
      - main
      - cicd
    paths:
      - "webapps/**"
  pull_request:
    branches:
      - main
      - cicd
    paths:
      - "webapps/**"
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_webapps: ${{ steps.set-outputs.outputs.changed_webapps }}
    steps:
      - uses: actions/checkout@v3

      - name: Store changed files in json array
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            webapps/fullstackproject/**
            webapps/main/**

      - name: Determine changed webapps
        id: set-outputs
        run: |
          # Array to store changed webapps
          changed=()

          # Check fullstack changes
          if [[ "${{ contains(steps.changed-files.outputs.all_changed_files, 'webapps/fullstackproject/') }}" == "true" ]]; then
            changed+=("fullstackproject")
          fi

          # Check main changes
          if [[ "${{ contains(steps.changed-files.outputs.all_changed_files, 'webapps/main/') }}" == "true" ]]; then
            changed+=("main")
          fi

          # Convert to JSON array and set output
          json_changed=$(jq -nc '$ARGS.positional' --args "${changed[@]}")
          echo "changed_webapps=$json_changed" >> $GITHUB_OUTPUT

  build-changed-webapps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.changed_webapps) }}
    needs: detect-changes
    steps:
      - name: Checkout changed_webapps
        run: |
          echo "Changed webapps: ${{ matrix.service }}"
          echo "raw json: ${{ needs.detect-changes.outputs.changed_webapps }}"

      - uses: actions/checkout@v3
      - name: Build Service
        run: |
          echo "Building ${{ matrix.service }}"
          cd "webapps/${{ matrix.service }}"
          docker compose build
