name: CI/CD for webapps

on:
  push:
    branches:
      - main
      - cicd
    paths:
      - "webapps/**"
  pull_request:
    branches:
      - main
      - cicd
    paths:
      - "webapps/**"
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_webapps: ${{ steps.set-outputs.outputs.changed_webapps }}
    steps:
      - uses: actions/checkout@v3

      - name: Store changed files in json array
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            webapps/fullstackproject/**
            webapps/main/**

      - name: Determine changed webapps
        id: set-outputs
        run: |
          changed=()

          # change detection
          if [[ -n "$(git diff --name-only HEAD^ HEAD -- webapps/fullstackproject/)" ]]; then
            changed+=("fullstackproject")
          fi

          if [[ -n "$(git diff --name-only HEAD^ HEAD -- webapps/main/)" ]]; then
            changed+=("main")
          fi

          # debug output
          echo "Files changed in fullstackproject:"
          git diff --name-only HEAD^ HEAD -- webapps/fullstackproject/ || echo "None"
          echo "Files changed in main:"
          git diff --name-only HEAD^ HEAD -- webapps/main/ || echo "None"

          # convert to JSON
          json_changed=$(jq -nc '$ARGS.positional' --args "${changed[@]}")
          echo "DEBUG: json_changed = $json_changed"
          echo "changed_webapps=$json_changed" >> $GITHUB_OUTPUT

      - name: checkout output
        run: |
          echo "final output value: ${{ steps.set-outputs.outputs.changed_webapps }}"

  build-changed-webapps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.changed_webapps) }}
    needs: detect-changes
    steps:
      - uses: actions/checkout@v3
      - name: Build Service
        run: |
          echo "Building ${{ matrix.service }}"
          cd "webapps/${{ matrix.service }}"
          docker compose build
