name: CI/CD for webapps

on:
  push:
    branches:
      - main
      - cicd
    paths:
      - "webapps/**"
  pull_request:
    branches:
      - main
      - cicd
    paths:
      - "webapps/**"
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_webapps: ${{ steps.set-outputs.outputs.changed_webapps }}
    steps:
      - uses: actions/checkout@v3

      - name: Detect Changed Paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            fullstack:
              - 'webapps/fullstackproject/**'
            main:
              - 'webapps/main/**'

      - name: Set Outputs
        id: set-outputs
        run: |
          # Initialize an array to store changed webapps
          changed=()

          # Check which paths were changed
          if [[ "${{ steps.filter.outputs.fullstack }}" == "true" ]]; then
            changed+=("fullstackproject")
          fi
          if [[ "${{ steps.filter.outputs.main }}" == "true" ]]; then
            changed+=("main")
          fi
          
          json_changed=$(jq -nc --argjson arr "$(printf '%s\n' "${changed[@]}" | jq -R . | jq -s .)" '$arr')
          echo "changed_webapps=$json_changed" >> $GITHUB_OUTPUT

  build-changed-webapps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.changed_webapps) }}
    needs: detect-changes
    steps:
      - uses: actions/checkout@v3
      - name: Build Service
        run: |
          cd webapps/${{ matrix.service }}
          docker compose build
